# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os 
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1106, 832)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 50, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 160, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(90, 280, 81, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 150, 81, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 290, 71, 16))
        self.label_5.setObjectName("label_5")
        self.PlainText = QtWidgets.QTextEdit(self.centralwidget)
        self.PlainText.setGeometry(QtCore.QRect(190, 120, 321, 87))
        self.PlainText.setObjectName("PlainText")
        self.CipherText = QtWidgets.QTextEdit(self.centralwidget)
        self.CipherText.setGeometry(QtCore.QRect(190, 250, 321, 87))
        self.CipherText.setObjectName("CipherText")
        self.Information = QtWidgets.QTextEdit(self.centralwidget)
        self.Information.setGeometry(QtCore.QRect(700, 120, 341, 87))
        self.Information.setObjectName("Information")
        self.Signature = QtWidgets.QTextEdit(self.centralwidget)
        self.Signature.setGeometry(QtCore.QRect(700, 260, 341, 87))
        self.Signature.setObjectName("Signature")
        self.GenerateKeys = QtWidgets.QPushButton(self.centralwidget)
        self.GenerateKeys.setGeometry(QtCore.QRect(650, 60, 93, 28))
        self.GenerateKeys.setObjectName("GenerateKeys")
        self.Encrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Encrypt.setGeometry(QtCore.QRect(180, 370, 93, 28))
        self.Encrypt.setObjectName("Encrypt")
        self.Decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.Decrypt.setGeometry(QtCore.QRect(350, 370, 93, 28))
        self.Decrypt.setObjectName("Decrypt")
        self.Sign = QtWidgets.QPushButton(self.centralwidget)
        self.Sign.setGeometry(QtCore.QRect(700, 380, 93, 28))
        self.Sign.setObjectName("Sign")
        self.Verify = QtWidgets.QPushButton(self.centralwidget)
        self.Verify.setGeometry(QtCore.QRect(930, 380, 93, 28))
        self.Verify.setObjectName("Verify")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1106, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "RSA CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Plain Text:"))
        self.label_3.setText(_translate("MainWindow", "Cipher Text:"))
        self.label_4.setText(_translate("MainWindow", "Information: "))
        self.label_5.setText(_translate("MainWindow", "Signature:"))
        self.GenerateKeys.setText(_translate("MainWindow", "Generate Keys"))
        self.Encrypt.setText(_translate("MainWindow", "Encrypt"))
        self.Decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.Sign.setText(_translate("MainWindow", "Sign"))
        self.Verify.setText(_translate("MainWindow", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
